### ISSUE TITLE
Material Receipt Candidates Handling Unit correction

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#123] opened 2017-02-13 12:35 UTC
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
No selection possibility to do the correction for Handling Units of a given Material Receipt Candidate.
#### Which are the steps to reproduce?
Open Material Receipt Candidates Window and see, that not Button/ Action is there to do that.
### What is the expected or desired behavior?
Provide an action that allows doing a Handling Unit correction. The action shall have a Material Receipt Candidate Line as Input. The Handling Unit Editor window shall open and display all processed Handling Units for the given input line. The user can select the lines and start the correction action in Handling Unit Editor.

**Comment by teosarca** [comment] 2017-02-13 12:37
duplicate of #122

**Closed by teosarca** 2017-02-13 12:37 UTC
Labels: enhancement

**Comment by metas-mk** [comment] 2017-02-13 12:41
thx :-)
