### ISSUE TITLE
Error when Pressing the Attribute Button

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#119] opened 2017-02-06 17:49 UTC
Error when pressing the Attribute Button

![image](https://cloud.githubusercontent.com/assets/13365687/22659172/f0870c3c-ec9c-11e6-8258-c60c445362b5.png)

**Comment by teosarca** [comment] 2017-02-07 09:29
NOTE: could not reproduce it on current baseline => it will be fixed on next rollout

**Comment by metas-mk** [comment] 2017-02-14 16:45
Quick Test. Works now.

**Comment by metas-mk** [comment] 2017-02-14 16:48
Created ReleaseNotes for 4.45.55

**Closed** 2017-02-14 16:47 UTC
Labels: bug, integrated
