### ISSUE TITLE
UOM Error if UOM is not piece

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui#69] opened 2016-11-29 11:02 UTC
1. open order window
2. create new order
3. add line
4. pick any product (e.g. Frisee) with UOM kg
6. NOK: error message

```
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Error: Failed to convert Qty=1 of product=P002732 from UOM=Stück to UOM=Kilogramm
```

**Comment by metas-mk** [comment] 2016-11-29 11:47
Orderline "add" leads to UOM error when Product not pce
- prepare a product which has m_product.UOM != pce (e.g. kg)
- create an order, orderline. select that product
--> leads to an error because of missing UOM concersion. The error is, that the UOM of product is not set correctly via callout in orderline after selecting product.

**Comment by teosarca** [comment] 2016-11-29 18:55
Fixed by https://github.com/metasfresh/metasfresh/commit/7d422589e3f76f4fb58282a38537676543c8d5a4

But please note that i had to change a bit the callout logic when user sets a product:
* UOM: set to product's stocking UOM
* Pricing UOM: temporary reset and will be set back from pricing (not visible for user)

Note to IT:
* pls also do regression on Swing client

**Closed** 2016-11-30 12:08 UTC
Labels: bug
